### ISSUE TITLE
activate sudo support

### ISSUE THREAD

**Issue by erighetto** [athenaspa/webdev#1]
RUN apt install sudo && \
usermod -aG sudo ${APPLICATION_USER} && \
echo "${APPLICATION_USER} ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${APPLICATION_USER}

**Comment by athenaspa** [comment]
https://github.com/athenaspa/webdev/commit/0fb8bfdab318e4a40e4aefd9ee5f5e9871eef96d solve
